[package]
authors = ["Paul Min"]
description = "Tool for manipulating and querying records on Transip Api"
edition = "2021"
license = "MIT"
name = "transipctl"
repository = "https://github.com/paulusminus/transipctl"
version = "0.1.0"

[dependencies]
pest = "2.7.4"
pest_derive = "2.7.4"
serde = "1.0.189"
serde_json = "1.0.107"
strum = { version = "0.25.0", features = ["derive"] }
thiserror = "1.0.49"
transip = "0.1.2"
