[package]
name = "transipctl"
description = "Tool for manipulating and querying record on Transip Api"
edition = "2021"
license = "MIT"
version = "0.1.0"

[dependencies]
pest = "2.7.4"
pest_derive = "2.7.4"
serde = "1.0.189"
serde_json = "1.0.107"
thiserror = "1.0.49"
transip = "0.1.0"
