'\" t
.TH "TRANSIPCTL" "1"
.nh
.ad l
.ss \n[.ss] 0
.SH "NAME"
transipctl \[em] Parse lines into commands to be executed on Transip Api Endpoint
.SH "SYNOPSIS"
\fBtransipctl\fR [\fIoptions\fR]
.SH "DESCRIPTION"
This command takes lines from stdin or the filename provided. Each line is interpreted as a command to
be executed on the Transip Api Endpoint. See \fI\f(BItransip\-command\fI\fR <https://crates.io/crates/transip\-command> for all
list of available commands.
.SH "OPTIONS"
<dl>
<dt class="option\-term" id="option\-transipctl\-\-v"><a class="option\-anchor" href="#option\-transipctl\-\-v"></a><code>\-v</code></dt>
<dt class="option\-term" id="option\-transipctl\-\-\-version"><a class="option\-anchor" href="#option\-transipctl\-\-\-version"></a><code>\-\-version</code></dt>
<dd class="option\-desc">Print version info and exit. This option cannot be combined with other options.</dd>
<dt class="option\-term" id="option\-transipctl\-filename"><a class="option\-anchor" href="#option\-transipctl\-filename"></a><code>&lt;filename&gt;</code></dt>
<dd class="option\-desc">Process the lines from &lt;filename&gt; and exit. This option cannot be combined with other options.</dd>
</dl>
.SH "EXAMPLES"
.sp
.RS 4
\h'-04' 1.\h'+01'Display the version and exit:
.sp
.RS 4
.nf
transipctl \-v
.fi
.RE
.RE
.sp
.RS 4
\h'-04' 2.\h'+01'Execute one command and exit:
.sp
.RS 4
.nf
echo "domain list" | transipctl
.fi
.RE
.RE
