'\" t
.TH "TRANSIPCTL" "1"
.nh
.ad l
.ss \n[.ss] 0
.SH "NAME"
transipctl \[em] Parse lines into commands to be executed on Transip Api Endpoint
.SH "SYNOPSIS"
\fBtransipctl\fR [\fIoptions\fR]
.SH "DESCRIPTION"
This command takes lines from stdin or the filename provided. Each line is interpreted as a command to 
be executed on the Transip Api Endpoint. See \fI\f(BItransip\-command\fI\fR <https://crates.io/crates/transip\-command> for all
list of available commands.
.SH "OPTIONS"
.sp
\fB\-v\fR, 
\fB\-\-version\fR
.RS 4
Print version info and exit. This option cannot be combined with other options.
.RE
.sp
\fB<filename>\fR
.RS 4
Process the lines from <filename> and exit. This option cannot be combined with other options.
.RE
.SH "EXAMPLES"
.sp
.RS 4
\h'-04' 1.\h'+01'Display the version and exit:
.sp
.RS 4
.nf
transipctl \-v
.fi
.RE
.RE
.sp
.RS 4
\h'-04' 2.\h'+01'Execute one command and exit:
.sp
.RS 4
.nf
echo "domain list" | transipctl
.fi
.RE
.RE
