[package]
name = "transip-command"
authors.workspace = true
description = "Parse a string and return a transip command"
edition.workspace = true
license.workspace = true
repository.workspace = true
version = "0.3.6"

[dependencies]
strum = { version = "0.25.0", features = ["derive"] }
thiserror = "1.0.51"

[features]
propagation = []
