[package]
name = "transip-command"
authors.workspace = true
description = "Parse a string and return a transip command"
edition.workspace = true
license.workspace = true
repository.workspace = true
version = "0.3.8"
rust-version = "1.64.0"

[dependencies]
strum = { version = "0.26.0", features = ["derive"] }
thiserror = "1.0.50"

[features]
propagation = []
